export const FILTER_LABELS: Record<string, string> = {
  weight_loss: 'Снижение веса',
  muscle_gain: 'Набор массы',
  better_nutrition: 'Здоровое питание',
  gut_health: 'Здоровье ЖКТ',
  sports_nutrition: 'Спортивное питание',
  diabetes: 'Контроль диабета',
  mental_wellness: 'Ментальное здоровье',
  pregnancy: 'Питание при беременности',
  nutrition_basics: 'Основы питания',
  meal_planning: 'Планирование рациона',
  supplements: 'Добавки и витамины',
  weight_management: 'Контроль веса',
  sports_performance: 'Спортивные результаты',
  chronic_conditions: 'Хронические заболевания',
  eating_disorders: 'Расстройства пищевого поведения',
  pediatric_nutrition: 'Детское питание',
  vegetarian: 'Вегетарианство',
  vegan: 'Веганство',
  gluten_free: 'Без глютена',
  lactose_free: 'Без лактозы',
  halal: 'Халяль',
  kosher: 'Кошер',
  one_time: 'Разовая консультация',
  plan: 'План питания',
  long_term: 'Длительное сопровождение',
  plant_based: 'Растительное питание',
  holistic: 'Холистический подход',
  mindful_eating: 'Осознанное питание',
  performance: 'Результативность',
  digestive_wellness: 'Здоровое пищеварение',
  research: 'Научный подход',
  ibs: 'СРК',
  metabolic_health: 'Метаболическое здоровье',
  clinical: 'Клиническое питание',
  family: 'Семейное питание',
  breastfeeding: 'Грудное вскармливание',
  pediatric: 'Педиатрия',
  budget_friendly: 'Бюджетное питание',
  meal_prep: 'Заготовки еды',
  practical: 'Практичный подход',
  ayurveda: 'Аюрведа',
  functional: 'Функциональная медицина',
}

export const formatFilterLabel = (value: string): string => {
  return FILTER_LABELS[value] || value.replace(/_/g, ' ')
}
